apiVersion: v1
kind: Service
metadata:
  name: content-service # Nombre DNS para este servicio
spec:
  selector:
    app: content-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP